Assignment 6.1

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

Note: Solution submitted via github must contain all the detailed steps.

In [57]:
# Notes : column stack is used here to combine columns

a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))


array([[1, 2],
       [2, 3],
       [3, 4]])

In [58]:
import numpy as np
# Function vander_func :
#  1st Param : x is a list
#  2nd Param : N is the order of power
#  3rd Param : sorting order 
def vander_func(x,N,increasing=False):
    if increasing:
        return np.sort(np.column_stack([x**(N-1-i) for i in range(N)]),axis=1)
    else:
        return np.column_stack([x**(N-1-i) for i in range(N)])
   
b=vander_func(np.array([1, 2, 5, 6]),3)
print("Vandermonde - default order :\n" , b)

a=vander_func(np.array([1, 2, 5, 6]),3,True)
print("Vandermonde - increasing order :\n" , a)

Vandermonde - default order :
 [[ 1  1  1]
 [ 4  2  1]
 [25  5  1]
 [36  6  1]]
Vandermonde - increasing order :
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  5 25]
 [ 1  6 36]]


In [59]:
x = np.array([1, 2, 5,6])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [25,  5,  1],
       [36,  6,  1]])

In [60]:
np.vander(x, N,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  5, 25],
       [ 1,  6, 36]])